### ISSUE TITLE
Help, angularjs plugin in eclipse didn't work

### ISSUE THREAD

**Issue by txgj** [angelozerr/angularjs-eclipse#155] opened 2015-07-08 08:28 UTC
I  did step by step  on getting started, but angularjs didn't work.
Please help me, thanks!

the error is :

eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/infer.js:301
      this.construct.apply(this, arguments);
TypeError: Cannot call method 'apply' of undefined
                     ^
    at Object.ctor
 (/eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/infer.js:301:22)
    at Injector.set (/eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/plugin/angular.js:37:49)
    at
 /eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/plugin/angular.js:106:5
    at fn.computeRet (
/eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/def.js:241:21)
    at Object.exports.IsCallee.constraint.addType (/eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/infer.js:368:9)
    at angular_regFieldCall (/eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/plugin/angular.js:166:22)
    at withWorklist 
(/eclipse/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/infer.js:799:21)
    at Object.CallExpression

**Comment by angelozerr** [comment] 2015-07-08 08:33
Please share your project which causes problem.

**Comment by prabsp** [comment] 2015-07-09 03:36
I too face the same problem. It occurs when loading any javascript libs (anglarjs, bootstrap, etc). So auto completion, angularjs explorer are not working.

**Comment by angelozerr** [comment] 2015-07-09 04:20
@prabsp it seems that it's a problem with a lot of load of JS files. To avoid that 1.0.0-SNAPSHOT (not released) http://oss.opensagres.fr/angularjs-eclipse/1.0.0-SNAPSHOT/ gives the capability to exclude path https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-1.0.0#includeexclude-tern-script-paths

**Comment by txgj** [comment] 2015-07-10 12:49
Hi,angelozerr, thank you very much.  But,  I can't  update the plugins  from  http://oss.opensagres.fr/angularjs-eclipse/1.0.0-SNAPSHOT/  ,  it reports the error that read time out when downloading  the  ternjs.jar.

**Comment by angelozerr** [comment] 2015-07-10 13:02
@txgj please share your project and tell me how to reproduce your problem. Thanks

**Comment by jabby** [comment] 2015-07-15 07:47
@angelozerr I think it's a network problem during the installation. Not a problem with tern.java

**Comment by dgolovin** [comment] 2015-07-24 00:55
@jabby, this seems to be related to ternjs update that was done right befor tagging for 0.10.0 release. When I use tern-java built from commit preceding ternjs update
``` shell
git checkout 113f1a17e0c40755a688368aee9a6d9f15909c05
```
everything works fine, see my comment [here](https://issues.jboss.org/browse/JBIDE-19694?focusedCommentId=13092500&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13092500).

I can easy replicate exception above with basic ionic project created 
```  shell
ionic start MyApp tabs
```
and get empty modules node in Angular Explorer.

**Comment by angelozerr** [comment] 2015-07-24 08:00
@dgolovin thanks for your comment. I will see your problem next month.

**Comment by angelozerr** [comment] 2015-07-24 08:04
@txgj please share your project and tell me how to reproduce your problem. Thanks

**Comment by sieira** [comment] 2015-07-27 18:15
I'm experiencing the same problem. I installed angularjs-eclipse via nodeclipse. Hints are working properly, if I use autocompletion in a js, it succeeds suggesting me 'angular', but when validating all the modules show the warning "'angular' is not defined".

I guess modules are not being registered (from tern's point of view), because angular explorer is not showing anything (only an empty project folder).

If I add node_modules folder to tern's script path, then, angular explorer detects all the scripts in the project, but it fails to detect any module within.

I'm running eclipse mars which already excludes node_modules folder from the build path.

Everithing is working fine on runtime, and tern console shows the same exception @txgj is getting. I've spent the whole day tracking the origin of this issue, and I got to a dead-end here.

**Comment by angelozerr** [comment] 2015-07-28 00:24
I van see this pb next month but Please Shane your project

**Comment by sieira** [comment] 2015-07-28 12:23
> I'm sorry about the extension of this comment, I tried to be brief but I wanted to give all the relevant information

Here you are [a sample minimal project](http://spacebar.fr/extra/public/AngularJS-test.tar.gz)
It's an express project which :

  - Creates a server listening on localhost:3000
  - Sends /public/views/index.html to the client.
  - Just for testing I included angular three different ways
   1. From **googleapis**:  Everything is fine on runtime, it doesn't affect eclipse's scope (intended to be used only on production)
   2. From **npm module** (see package.json): The file is never sent to the client (node_modules is not on express path (and should not, I still wonder what's the point of including angular with the server-side modules, and why does google recommend it...)
   3. From **/libs/angular.js**: Same than 1

![post1](https://cloud.githubusercontent.com/assets/13233859/8930326/3ad3b714-352d-11e5-8142-37e60f2d7f63.png)

Problems are those described in my comment above:

1. Autocompletion works fine
2. Angular var as well as it's module method are suggested when writing js files, but once that done, a warning is shown saying 'angular' is not defined.
 1. Including angular.js in the HTML doesn't solve the issue
 2. Including angular.js within the express path doesn't solve de issue
3. Angular explorer doesn't show anything (just empty script and modules dirs)
  1. **Including index.html to tern's script path partially solves the issue** (this is not done in the test project), angular explorer will detect the module in the file (the project folder will detect the scripts but not their modules) ** the 'angular' is not defined warning will still be shown
![angular explorer](https://cloud.githubusercontent.com/assets/13233859/8930632/d27c37a6-352f-11e5-8955-3be56d2b9e6a.png)

So, including my HTML in tern's path corrected the main problem, now modules are being loaded and available for auto-completion. Including my entire public directory did it as well

![still one](https://cloud.githubusercontent.com/assets/13233859/8930911/6506a7b2-3532-11e5-82c9-4c9259a49a95.png)

# BUT #

If you add any other library to the path (moving /vault/ui-bootstrap-tpls-0.13.1.min to /public/libs/) and you validate, the infamous exception is triggered again, and tern fails to detect modules

![ultimo](https://cloud.githubusercontent.com/assets/13233859/8931060/cc3a730e-3533-11e5-9f5a-674716712ec6.png)

I'm not sure if this comes from our misunderstanding about how tern works, or it's a real bug, and in the latter case, I wonder if it may be a tern's bug, not related to your project.

I hope this information will be of some use, please, don't hesitate to contact me if I can be of some help here, thank you for your time and for your magnificent job with this module.

**Comment by angelozerr** [comment] 2015-07-28 12:41
Thanks @sieira ! I will study your project next month.

**Comment by sieira** [comment] 2015-07-28 13:39
Ok I managed to isolate the problem (sorry for the insistence, I guess you have better things to do).

While this works:

    /**
     * Angular module
     */
    (function() {
        angular.module("angular-test",[])
        .controller('TestController', ['$scope', function($scope) {
            $scope.test = 'Hola!';
        )]);
    })();

This doesn't:

    /**
     * Angular module
     */
    (function() {
        angular.module("angular-test",[])
        /**
         * This comment will make tern explode
         */
         .controller('TestController', ['$scope', function($scope) {
             $scope.test = 'Hola!';
        )]);
    })();

I guess this should be reported to tern

**Comment by angelozerr** [comment] 2015-07-28 18:38
Thanks Sieira for your info! I will try it next month.

**Comment by swal** [comment] 2015-07-31 10:48
I have the same issues as Sieira when following the angular-phonecat tutorial... By limiting the number of scripts in the script path of tern, it doesn't give errors any more, but then the auto-completion is very limited. If I add some more scripts, then this exception keeps on showing up...

**Comment by angelozerr** [comment] 2015-08-02 10:15
@sieira @dgolovin @txgj @prabsp I have fixed the problem. Please install 1.0.0-SNAPSHOT and tell me if it works for you.

**Comment by sieira** [comment] 2015-08-02 15:52
@angelozerr Thanks a lot. Everything is running perfectly.

**Comment by angelozerr** [comment] 2015-08-02 16:50
>  Thanks a lot. Everything is running perfectly

Cool, I close this issue. Thanks @sieira for your very helpful information!

> Where all this "accordion" stuff comes from dndLists. I don't know if it is the expected behaviour.

Please create a new issue if you have other problem.

**Closed by angelozerr** 2015-08-02 16:50 UTC
